#!/bin/sh

[ -e /lib/firmware/$FIRMWARE ] && exit 0

. /lib/functions/caldata.sh

board=$(board_name)

case "$FIRMWARE" in
"ath11k/IPQ9574/hw1.0/cal-ahb-c000000.wifi.bin")
	case "$board" in
	jio,jidu6811)
		caldata_extract "0:ART" 0x1000 0x20000
		;;
	esac
	;;
"ath11k/QCN9074/hw1.0/cal-pci-0001:01:00.0.bin")
	case "$board" in
	jio,jidu6811)
		caldata_extract "0:ART" 0x4c000 0x20000
		;;
	esac
	;;
*)
	exit 1
	;;
esac
